include:
- ./func/*
kind: ArchiveUploadSpec
name: func-ISSz

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-activity-type-7d292baa-698e-4cdd-a67c-1e767718e336
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-activity-type
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-ISSz
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-26T16:05:50Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-activity-type
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-activity-type
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-activity-type-7d292baa-698e-4cdd-a67c-1e767718e336
      namespace: default
  requestsPerPod: 10000
  resources: {}
