include:
- ./func/*
kind: ArchiveUploadSpec
name: func-5dQP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-activity-type-12f718f3-0a93-46e6-abea-7c162d09ed09
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-activity-type
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-5dQP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-05-23T18:11:54Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-activity-type
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-activity-type
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_enums
    packageref:
      name: fn-get-activity-type-12f718f3-0a93-46e6-abea-7c162d09ed09
      namespace: default
  requestsPerPod: 1
  resources: {}
