apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 34d5a35f-30c5-4d83-90cd-a4b50652bd6a
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-activity-type
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/activity_type
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/activity_type
